# Generated by Django 4.2.1 on 2023-05-27 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inspector", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resumecheck",
            old_name="datetime",
            new_name="created",
        ),
    ]
