# Generated by Django 4.2.1 on 2023-05-28 05:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inspector", "0002_rename_datetime_resumecheck_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interview",
            options={
                "ordering": ["id"],
                "verbose_name": "Интервью",
                "verbose_name_plural": "Интервью",
            },
        ),
        migrations.AlterModelOptions(
            name="resume",
            options={
                "ordering": ["id"],
                "verbose_name": "Резюме",
                "verbose_name_plural": "Резюме",
            },
        ),
        migrations.AlterModelOptions(
            name="resumecheck",
            options={
                "ordering": ["id"],
                "verbose_name": "Проверка резюме",
                "verbose_name_plural": "Проверка резюме",
            },
        ),
        migrations.AlterModelOptions(
            name="resumefile",
            options={
                "ordering": ["id"],
                "verbose_name": "Файл резюме",
                "verbose_name_plural": "Файл резюме",
            },
        ),
    ]
