# Generated by Django 4.2.1 on 2023-05-28 05:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["id"],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователь",
            },
        ),
        migrations.AlterModelOptions(
            name="emailvalidation",
            options={
                "ordering": ["id"],
                "verbose_name": "Код проверки почты",
                "verbose_name_plural": "Код проверки почты",
            },
        ),
        migrations.AlterModelOptions(
            name="telegramuser",
            options={
                "ordering": ["id"],
                "verbose_name": "Telegram пользователь",
                "verbose_name_plural": "Telegram пользователь",
            },
        ),
    ]
