version: '3.7'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=scb_hr
      - POSTGRES_PASSWORD=supermegapassword
      - POSTGRES_DB=scb_hr
    ports:
      - "5432:5432"

  web:
    build: .
    command:
      - /bin/sh
      - -c
      - |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py loaddata /app/fixtures.json
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  redis:
    image: redis:6-alpine

  worker:
    build: .
    command: sh -c "celery -A scb_hr worker --loglevel=info"
    env_file:
      - .env
    depends_on:
      - web
      - redis

  beat:
    build: .
    command: sh -c "celery -A scb_hr beat --loglevel=info"
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - worker

  telegram_polling:
    build: .
    command: sh -c "python telegram_polling.py"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: