# Generated by Django 4.2.1 on 2023-05-26 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("position", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="EmploymentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("FULL", "Полный рабочий день"),
                            ("PART", "Частичная занятость"),
                            ("REMOTE", "Удалённая работа"),
                            ("INTERNSHIP", "Стажировка"),
                        ],
                        max_length=16,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, verbose_name="Название")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Фотография"
                    ),
                ),
                ("street", models.CharField(max_length=1024, verbose_name="Улица")),
                ("house_number", models.CharField(max_length=1024, verbose_name="Дом")),
                (
                    "office_number",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Номер офиса",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offices",
                        to="vacancy.city",
                        verbose_name="город",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Specialisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="Название"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "employment_types",
                    models.ManyToManyField(
                        related_name="vacancies",
                        to="vacancy.employmenttype",
                        verbose_name="Тип занятости",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to="vacancy.office",
                        verbose_name="офис",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to="position.position",
                        verbose_name="Должность",
                    ),
                ),
                (
                    "specialisations",
                    models.ManyToManyField(
                        related_name="vacancies",
                        to="vacancy.specialisation",
                        verbose_name="Специализация",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkYears",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("INTERN", "Без опыта"),
                            ("JUNIOR", "1-3 года"),
                            ("MIDDLE", "3-5 лет"),
                            ("SENIOR", "5+ лет"),
                        ],
                        max_length=16,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VacancyCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "visible_for_candidate",
                    models.BooleanField(
                        default=True, verbose_name="Видим для кандидата"
                    ),
                ),
                (
                    "inspectors",
                    models.ManyToManyField(
                        related_name="as_inspector",
                        to="position.position",
                        verbose_name="Должности, которые могут согласовать",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="vacancy.vacancy",
                        verbose_name="Вакансия",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="vacancy",
            name="work_years",
            field=models.ManyToManyField(
                related_name="vacancies",
                to="vacancy.workyears",
                verbose_name="Опыт работы",
            ),
        ),
    ]
