# Generated by Django 4.2.1 on 2023-05-28 05:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vacancy", "0002_alter_city_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={
                "ordering": ["id"],
                "verbose_name": "Город",
                "verbose_name_plural": "Город",
            },
        ),
        migrations.AlterModelOptions(
            name="employmenttype",
            options={
                "ordering": ["id"],
                "verbose_name": "Тип занятости",
                "verbose_name_plural": "Тип занятости",
            },
        ),
        migrations.AlterModelOptions(
            name="office",
            options={
                "ordering": ["id"],
                "verbose_name": "Офис",
                "verbose_name_plural": "Офис",
            },
        ),
        migrations.AlterModelOptions(
            name="specialisation",
            options={
                "ordering": ["id"],
                "verbose_name": "Специализация вакансии",
                "verbose_name_plural": "Специализация вакансии",
            },
        ),
        migrations.AlterModelOptions(
            name="vacancy",
            options={
                "ordering": ["id"],
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансия",
            },
        ),
        migrations.AlterModelOptions(
            name="vacancycheck",
            options={
                "ordering": ["id"],
                "verbose_name": "Проверка вакансии",
                "verbose_name_plural": "Проверка вакансии",
            },
        ),
        migrations.AlterModelOptions(
            name="workyears",
            options={
                "ordering": ["id"],
                "verbose_name": "Требуемый опыт",
                "verbose_name_plural": "Требуемый опыт",
            },
        ),
    ]
