# Generated by Django 4.2.1 on 2023-05-26 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Начало работы")),
                (
                    "finish_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Конец работы"
                    ),
                ),
                (
                    "company",
                    models.CharField(max_length=1024, verbose_name="Организация"),
                ),
                (
                    "position",
                    models.CharField(max_length=1024, verbose_name="Должность"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_experiences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Резюме",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=1024, verbose_name="Заведение")),
                (
                    "direction",
                    models.CharField(max_length=1024, verbose_name="Направление"),
                ),
                ("start_date", models.DateField(verbose_name="Начало обучения")),
                (
                    "finish_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Конец обучения"
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Резюме",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Почта"),
                            ("PHONE", "Телефон"),
                            ("ADDRESS", "Адрес"),
                            ("TELEGRAM", "Telegram"),
                            ("VK", "ВКонтакте"),
                        ],
                        max_length=8,
                        verbose_name="Тип",
                    ),
                ),
                ("value", models.CharField(max_length=32, verbose_name="Значение")),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кандидат",
                    ),
                ),
            ],
        ),
    ]
