# Generated by Django 4.2.1 on 2023-05-28 05:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["id"],
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакт",
            },
        ),
        migrations.AlterModelOptions(
            name="education",
            options={
                "ordering": ["id"],
                "verbose_name": "Запись об образовании",
                "verbose_name_plural": "Запись об образовании",
            },
        ),
        migrations.AlterModelOptions(
            name="workexperience",
            options={
                "ordering": ["id"],
                "verbose_name": "Опыт работы",
                "verbose_name_plural": "Опыт работы",
            },
        ),
    ]
