# Generated by Django 4.2.1 on 2023-05-28 05:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("position", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organisation",
            options={
                "ordering": ["id"],
                "verbose_name": "Организация",
                "verbose_name_plural": "Организация",
            },
        ),
        migrations.AlterModelOptions(
            name="position",
            options={
                "ordering": ["id"],
                "verbose_name": "Должность",
                "verbose_name_plural": "Должность",
            },
        ),
    ]
